#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestAzure.Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="demo")]
	public partial class Dep_LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDepartment(Department instance);
    partial void UpdateDepartment(Department instance);
    partial void DeleteDepartment(Department instance);
    #endregion
		
		public Dep_LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["demoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Dep_LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Dep_LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Dep_LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Dep_LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Department> Departments
		{
			get
			{
				return this.GetTable<Department>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.allProcedures")]
		public ISingleResult<allProceduresResult> allProcedures()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<allProceduresResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departments")]
	public partial class Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDepto;
		
		private string _nbrDepto;
		
		private System.Nullable<int> _idEncargado;
		
		private string _ubicacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDeptoChanging(int value);
    partial void OnIdDeptoChanged();
    partial void OnnbrDeptoChanging(string value);
    partial void OnnbrDeptoChanged();
    partial void OnidEncargadoChanging(System.Nullable<int> value);
    partial void OnidEncargadoChanged();
    partial void OnubicacionChanging(string value);
    partial void OnubicacionChanged();
    #endregion
		
		public Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]

    
        public int IdDepto
		{
			get
			{
				return this._IdDepto;
			}
			set
			{
				if ((this._IdDepto != value))
				{
					this.OnIdDeptoChanging(value);
					this.SendPropertyChanging();
					this._IdDepto = value;
					this.SendPropertyChanged("IdDepto");
					this.OnIdDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrDepto", DbType="NVarChar(50)")]
		public string nbrDepto
		{
			get
			{
				return this._nbrDepto;
			}
			set
			{
				if ((this._nbrDepto != value))
				{
					this.OnnbrDeptoChanging(value);
					this.SendPropertyChanging();
					this._nbrDepto = value;
					this.SendPropertyChanged("nbrDepto");
					this.OnnbrDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEncargado", DbType="Int")]
		public System.Nullable<int> idEncargado
		{
			get
			{
				return this._idEncargado;
			}
			set
			{
				if ((this._idEncargado != value))
				{
					this.OnidEncargadoChanging(value);
					this.SendPropertyChanging();
					this._idEncargado = value;
					this.SendPropertyChanged("idEncargado");
					this.OnidEncargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="NVarChar(50)")]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this.OnubicacionChanging(value);
					this.SendPropertyChanging();
					this._ubicacion = value;
					this.SendPropertyChanged("ubicacion");
					this.OnubicacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class allProceduresResult
	{
		
		private string _SPECIFIC_NAME;
		
		public allProceduresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPECIFIC_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string SPECIFIC_NAME
		{
			get
			{
				return this._SPECIFIC_NAME;
			}
			set
			{
				if ((this._SPECIFIC_NAME != value))
				{
					this._SPECIFIC_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
