#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestAzure.Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="demo")]
	public partial class Emp_LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public Emp_LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["demoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Emp_LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Emp_LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Emp_LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Emp_LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getallDep")]
		public ISingleResult<getallDepResult> getallDep()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getallDepResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarxDeptoId")]
		public ISingleResult<listarxDeptoIdResult> listarxDeptoId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dpto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dpto);
			return ((ISingleResult<listarxDeptoIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarxDeptoNmbre")]
		public ISingleResult<listarxDeptoNmbreResult> listarxDeptoNmbre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dpto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dpto);
			return ((ISingleResult<listarxDeptoNmbreResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employees")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmpleado;
		
		private string _nbrEmpleado;
		
		private System.Nullable<int> _IdDepto;
		
		private string _fechaIngreso;
		
		private string _fotoStr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpleadoChanging(int value);
    partial void OnIdEmpleadoChanged();
    partial void OnnbrEmpleadoChanging(string value);
    partial void OnnbrEmpleadoChanged();
    partial void OnIdDeptoChanging(System.Nullable<int> value);
    partial void OnIdDeptoChanged();
    partial void OnfechaIngresoChanging(string value);
    partial void OnfechaIngresoChanged();
    partial void OnfotoStrChanging(string value);
    partial void OnfotoStrChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					this.OnIdEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdEmpleado = value;
					this.SendPropertyChanged("IdEmpleado");
					this.OnIdEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrEmpleado", DbType="NVarChar(50)")]
		public string nbrEmpleado
		{
			get
			{
				return this._nbrEmpleado;
			}
			set
			{
				if ((this._nbrEmpleado != value))
				{
					this.OnnbrEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._nbrEmpleado = value;
					this.SendPropertyChanged("nbrEmpleado");
					this.OnnbrEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepto", DbType="Int")]
		public System.Nullable<int> IdDepto
		{
			get
			{
				return this._IdDepto;
			}
			set
			{
				if ((this._IdDepto != value))
				{
					this.OnIdDeptoChanging(value);
					this.SendPropertyChanging();
					this._IdDepto = value;
					this.SendPropertyChanged("IdDepto");
					this.OnIdDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="NVarChar(45)")]
		public string fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this.OnfechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._fechaIngreso = value;
					this.SendPropertyChanged("fechaIngreso");
					this.OnfechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fotoStr", DbType="NVarChar(100)")]
		public string fotoStr
		{
			get
			{
				return this._fotoStr;
			}
			set
			{
				if ((this._fotoStr != value))
				{
					this.OnfotoStrChanging(value);
					this.SendPropertyChanging();
					this._fotoStr = value;
					this.SendPropertyChanged("fotoStr");
					this.OnfotoStrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class getallDepResult
	{
		
		private int _IdDepto;
		
		private string _nbrDepto;
		
		private System.Nullable<int> _idEncargado;
		
		private string _ubicacion;
		
		public getallDepResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepto", DbType="Int NOT NULL")]
		public int IdDepto
		{
			get
			{
				return this._IdDepto;
			}
			set
			{
				if ((this._IdDepto != value))
				{
					this._IdDepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrDepto", DbType="NVarChar(50)")]
		public string nbrDepto
		{
			get
			{
				return this._nbrDepto;
			}
			set
			{
				if ((this._nbrDepto != value))
				{
					this._nbrDepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEncargado", DbType="Int")]
		public System.Nullable<int> idEncargado
		{
			get
			{
				return this._idEncargado;
			}
			set
			{
				if ((this._idEncargado != value))
				{
					this._idEncargado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="NVarChar(50)")]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this._ubicacion = value;
				}
			}
		}
	}
	
	public partial class listarxDeptoIdResult
	{
		
		private string _nbrEmpleado;
		
		private int _IdEmpleado;
		
		private string _fechaIngreso;
		
		public listarxDeptoIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrEmpleado", DbType="NVarChar(50)")]
		public string nbrEmpleado
		{
			get
			{
				return this._nbrEmpleado;
			}
			set
			{
				if ((this._nbrEmpleado != value))
				{
					this._nbrEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", DbType="Int NOT NULL")]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					this._IdEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="NVarChar(45)")]
		public string fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this._fechaIngreso = value;
				}
			}
		}
	}
	
	public partial class listarxDeptoNmbreResult
	{
		
		private string _nbrEmpleado;
		
		private int _IdEmpleado;
		
		private string _fechaIngreso;
		
		public listarxDeptoNmbreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrEmpleado", DbType="NVarChar(50)")]
		public string nbrEmpleado
		{
			get
			{
				return this._nbrEmpleado;
			}
			set
			{
				if ((this._nbrEmpleado != value))
				{
					this._nbrEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", DbType="Int NOT NULL")]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					this._IdEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="NVarChar(45)")]
		public string fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this._fechaIngreso = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
